import { z } from "zod";

// ============================================================================
// WIDGET TYPES
// ============================================================================
export const WidgetTypeSchema = z.enum([
    "kpi",
    "line",
    "area",
    "bar",
    "pie",
    "donut",
    "table",
    "cohort",
    "funnel",
    "map",
    "scatter",
    "filter",
    "markdown",
]);

export type WidgetType = z.infer<typeof WidgetTypeSchema>;

// ============================================================================
// WIDGET SPEC
// ============================================================================
export const WidgetSpecSchema = z.object({
    id: z.string(),
    title: z.string(),
    description: z.string().optional(),
    type: WidgetTypeSchema,
    goal: z.string().optional(),
    queryId: z.string().optional(),

    // Chart encoding
    encoding: z.object({
        x: z.object({
            field: z.string(),
            type: z.enum(["temporal", "nominal", "ordinal", "quantitative"]),
            format: z.string().optional(),
        }).optional(),
        y: z.object({
            field: z.string(),
            type: z.enum(["temporal", "nominal", "ordinal", "quantitative"]),
            format: z.string().optional(),
        }).optional(),
        color: z.object({
            field: z.string().optional(),
            scheme: z.string().optional(),
        }).optional(),
    }).optional(),

    // KPI specific
    kpiConfig: z.object({
        valueField: z.string(),
        format: z.enum(["number", "currency", "percent", "compact"]),
        prefix: z.string().optional(),
        suffix: z.string().optional(),
        comparison: z.object({
            type: z.enum(["previous_period", "target", "none"]),
            value: z.number().optional(),
            showDelta: z.boolean(),
        }).optional(),
    }).optional(),

    // Table specific
    tableConfig: z.object({
        columns: z.array(z.object({
            field: z.string(),
            header: z.string(),
            width: z.number().optional(),
            format: z.string().optional(),
        })),
        pageSize: z.number().optional(),
    }).optional(),

    // Vega-Lite spec (generated by backend)
    vegaSpec: z.any().optional(),

    // Interactions
    interactions: z.object({
        onClick: z.enum(["filter", "drilldown", "link", "none"]).optional(),
        targets: z.array(z.string()).optional(),
    }).optional(),

    // AI insight for this widget
    insight: z.string().optional(),

    // UI state
    ui: z.object({
        locked: z.boolean().optional(),
        loading: z.boolean().optional(),
        error: z.string().optional(),
    }).optional(),

    // Embedded data (for static dashboard view)
    data: z.array(z.record(z.string(), z.any())).optional(),
});

export type WidgetSpec = z.infer<typeof WidgetSpecSchema>;

// ============================================================================
// LAYOUT
// ============================================================================
export const LayoutItemSchema = z.object({
    i: z.string(), // Widget ID
    x: z.number(),
    y: z.number(),
    w: z.number(),
    h: z.number(),
    minW: z.number().optional(),
    minH: z.number().optional(),
    maxW: z.number().optional(),
    maxH: z.number().optional(),
    static: z.boolean().optional(),
});

export type LayoutItem = z.infer<typeof LayoutItemSchema>;

// ============================================================================
// FILTERS
// ============================================================================
export const FilterSchema = z.object({
    id: z.string(),
    dimension: z.string(),
    label: z.string(),
    type: z.enum(["date-range", "select", "multi-select", "search"]),
    value: z.any(),
    options: z.array(z.object({
        label: z.string(),
        value: z.any(),
    })).optional(),
});

export type Filter = z.infer<typeof FilterSchema>;

// ============================================================================
// QUERY
// ============================================================================
export const QuerySchema = z.object({
    id: z.string(),
    sql: z.string(),
    params: z.record(z.string(), z.any()).optional(),
    widgetIds: z.array(z.string()),
    status: z.enum(["pending", "running", "success", "error"]),
    executionTime: z.number().optional(),
    rowCount: z.number().optional(),
    error: z.string().optional(),
});

export type Query = z.infer<typeof QuerySchema>;

// ============================================================================
// QA CHECK
// ============================================================================
export const QACheckSchema = z.object({
    id: z.string(),
    type: z.enum(["grain", "fanout", "null", "empty", "outlier"]),
    status: z.enum(["pass", "warn", "fail"]),
    message: z.string(),
    widgetId: z.string().optional(),
    queryId: z.string().optional(),
    suggestion: z.string().optional(),
});

export type QACheck = z.infer<typeof QACheckSchema>;

// ============================================================================
// DASHBOARD
// ============================================================================
export const DashboardSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string().optional(),
    originalQuery: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
    createdBy: z.string().optional(),

    widgets: z.array(WidgetSpecSchema),
    layout: z.array(LayoutItemSchema),
    filters: z.array(FilterSchema),
    queries: z.array(QuerySchema),
    qaChecks: z.array(QACheckSchema).optional(),
    insights: z.array(z.string()).optional(),
    actionablePlan: z.string().optional(),

    // Recipe reference
    recipeId: z.string().optional(),

    // Semantic context
    semantic: z.object({
        metrics: z.array(z.object({
            slug: z.string(),
            name: z.string(),
            sql_definition: z.string(),
        })),
        dimensions: z.array(z.object({
            slug: z.string(),
            name: z.string(),
            table_name: z.string(),
        })),
    }).optional(),
});

export type Dashboard = z.infer<typeof DashboardSchema>;

// ============================================================================
// DASHBOARD ENVELOPE (Backend response)
// ============================================================================
export const DashboardEnvelopeSchema = z.object({
    runId: z.string(),
    status: z.enum(["pending", "running", "completed", "failed"]),
    dashboard: DashboardSchema.optional(),
    error: z.string().optional(),
    startedAt: z.string(),
    completedAt: z.string().optional(),
    durationMs: z.number().optional(),
});

export type DashboardEnvelope = z.infer<typeof DashboardEnvelopeSchema>;

// ============================================================================
// RUN EVENTS (Streaming)
// ============================================================================
export const StepStatusSchema = z.enum(["queued", "running", "done", "warn", "fail"]);
export type StepStatus = z.infer<typeof StepStatusSchema>;

export const AgentStepSchema = z.enum([
    "schema",
    "kpi",
    "plan",
    "policy",
    "semantic",
    "sql",
    "sample",
    "qa",
    "execute",
    "viz",
    "narrative",
    "persist",
]);
export type AgentStep = z.infer<typeof AgentStepSchema>;

export interface RunStepEvent {
    type: "step";
    step: AgentStep;
    status: StepStatus;
    message?: string;
    ts: string;
}

export interface PartialDashboardEvent {
    type: "partial_dashboard";
    dashboard: Partial<Dashboard>;
    ts: string;
}

export interface PartialResultsEvent {
    type: "partial_results";
    queryId: string;
    rowsPreview: any[];
    ts: string;
}

export interface FinalEvent {
    type: "final";
    envelope: DashboardEnvelope;
    ts: string;
}

export interface ErrorEvent {
    type: "error";
    message: string;
    ts: string;
}

export interface LogEvent {
    type: "log";
    message: string;
    level: "info" | "warn" | "error";
    step?: AgentStep;
    ts: string;
}

export type RunEvent =
    | RunStepEvent
    | PartialDashboardEvent
    | PartialResultsEvent
    | LogEvent
    | FinalEvent
    | ErrorEvent;

// ============================================================================
// RECIPE / TEMPLATE
// ============================================================================
export const RecipeParameterSchema = z.object({
    id: z.string(),
    name: z.string(),
    label: z.string(),
    type: z.enum(["string", "number", "date", "date-range", "select", "multi-select"]),
    required: z.boolean(),
    defaultValue: z.any().optional(),
    options: z.array(z.object({
        label: z.string(),
        value: z.any(),
    })).optional(),
});

export type RecipeParameter = z.infer<typeof RecipeParameterSchema>;

export const RecipeSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string().optional(),
    category: z.string().optional(),
    parameters: z.array(RecipeParameterSchema),
    previewImage: z.string().optional(),
    usageCount: z.number().optional(),
    createdBy: z.string().optional(),
    tags: z.array(z.string()).optional(),
});

export type Recipe = z.infer<typeof RecipeSchema>;

// ============================================================================
// SEMANTIC CATALOG
// ============================================================================
export const SemanticMetricSchema = z.object({
    slug: z.string(),
    name: z.string(),
    description: z.string().optional(),
    sql_definition: z.string(),
    agg_type: z.string(),
    base_table: z.string(),
    tags: z.array(z.string()).optional(),
    owner: z.string().optional(),
    lastUpdated: z.string().optional(),
});

export type SemanticMetric = z.infer<typeof SemanticMetricSchema>;

export const SemanticDimensionSchema = z.object({
    slug: z.string(),
    name: z.string(),
    description: z.string().optional(),
    type: z.string(),
    table_name: z.string(),
    hierarchy: z.array(z.string()).optional(),
});

export type SemanticDimension = z.infer<typeof SemanticDimensionSchema>;

export interface DataSource {
    id: string;
    name: string;
    type: string;
    details: string;
    status: "Connected" | "Disconnected" | "Connecting" | "Error" | "Auth Error";
    lastSync: string;
    icon: string;
    connectionString?: string;
}
